language : python
sudo: false
matrix:
  include:
     - python: "3.5"
       env: BUILD_DOCS=true

before_install:
  - git clone https://github.com/danielballan/nsls2-ci --branch docs-fixes --single-branch ~/ci_scripts
  - ~/ci_scripts/install_conda.sh

script:
  - |
    if [ $BUILD_DOCS == true ]; then
      pip install sphinx_rtd_theme
      pip install sphinxcontrib-napoleon
      cd $TRAVIS_BUILD_DIR/..
      cd docs
      make html
    fi

after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'NSLS-II/docs' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then
      echo "Uploading documentation"
      cd $TRAVIS_BUILD_DIR
      openssl aes-256-cbc -K $encrypted_a692684451b6_key -iv $encrypted_a692684451b6_iv -in NSLS-II-docs-deploy.enc -out NSLS-II-docs-deploy -d
      eval `ssh-agent -s`
      chmod 600 NSLS-II-docs-deploy
      ssh-add NSLS-II-docs-deploy
      git config --global user.email "Travis@nomail"
      git config --global user.name "Travis"
      git config --global push.default simple
      cd ..
      git clone git@github.com:NSLS-II/NSLS-II.github.io.git ./doc-repo
      cd doc-repo/
      git checkout --orphan temp_branch
      rsync -r $TRAVIS_BUILD_DIR/build/html/* .
      if [ -n "$TRAVIS_TAG" ]; then
        cp -R dev $TRAVIS_TAG;
      fi
      git add -A
      git commit -m "Documentation build of top-level 'docs' commit $TRAVIS_COMMIT"
      git branch -D master
      git branch -m master
      git push --set-upstream origin master --force
    fi
